In [50]:
import numpy as np
import pandas as pd

In [51]:
final_df=pd.read_csv('final.csv')

In [52]:
final_df.head()
final_df.describe()

c:\Users\ramte\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:52: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,match_id,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
count,1.117210e+05,111721.000000,111721.000000,111721.000000,111721.000000,111721.000000,1.117050e+05,111721.000000
mean,9.226578e+05,94.768719,62.487402,7.494285,168.742170,7.587475,NaN,0.512903
std,3.763858e+05,51.081266,33.465263,2.173986,30.689233,2.341020,NaN,0.499836
min,3.359820e+05,-5.000000,-3.000000,0.000000,62.000000,0.000000,-inf,0.000000
25%,5.483430e+05,55.000000,34.000000,6.000000,149.000000,6.391304,7.348315e+00,0.000000
50%,1.082600e+06,94.000000,63.000000,8.000000,168.000000,7.611940,9.109091e+00,1.000000
75%,1.254095e+06,133.000000,91.000000,9.000000,188.000000,8.848485,1.136842e+01,1.000000
max,1.426312e+06,287.000000,119.000000,10.000000,287.000000,36.000000,inf,1.000000

In [53]:
final_df.head()
final_df.dropna(inplace=True)
final_df=final_df[final_df['balls_left']!=0]

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x=final_df.iloc[:,:-1]
y=final_df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
num=x.select_dtypes('number').columns
num
cat=x.drop(columns=num).columns

Index(['batting_team', 'bowling_team', 'city'], dtype='object')

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler

trf = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, drop='first'),cat),
         ('num',MinMaxScaler(),num)
    ],
    remainder='passthrough'
)

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [59]:
pipe=Pipeline([
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear')),
] )

In [60]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  Index(['batting_team', 'bowling_team', 'city'], dtype='object')),
                                                 ('num', MinMaxScaler(),
                                                  Index(['match_id', 'runs_left', 'balls_left', 'wickets_left', 'total_runs_x',
       'crr', 'rrr'],
      dtype='object'))])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [61]:
y_pred=pipe.predict(X_test)

In [77]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [63]:
accuracy_score(y_test,y_pred)

0.8066828041197969

In [88]:
from sklearn.model_selection import GroupShuffleSplit

X = final_df.drop(columns=['result', 'match_id'])
y = final_df['result']
groups = final_df['match_id']

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, test_idx = next(gss.split(X, y, groups))

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

In [89]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler

num=X.select_dtypes('number').columns
num
cat=X.drop(columns=num).columns

trf = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, drop='first'),cat),
         ('num',MinMaxScaler(),num)
    ],
    remainder='passthrough'
)

In [78]:
from sklearn.ensemble import  (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


l=[]
models = {
    'Logistic Regression': LogisticRegression(),
    'KNN': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Naive Bayes': GaussianNB(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
}


for i,j in models.items():

    pipeline=Pipeline([
        ('1',trf),
        ('2',j)
    ])

    pipeline.fit(X_train,y_train)
    y_pred=pipeline.predict(X_test)
    a=accuracy_score(y_pred,y_test)
    b=precision_score(y_pred,y_test)
    c=recall_score(y_pred,y_test)
    d=f1_score(y_pred,y_test)
    dict={
        "Model":i,
        "accuracy":a,
        "precision_score":b,
        "recall_score":c,
        "f1_score":d
    }
    l.append(dict)
df=pd.DataFrame(l)

In [84]:
df.sort_values(['f1_score'],ascending=False)

                 Model  accuracy  precision_score  recall_score  f1_score
7             AdaBoost  0.767368         0.756442      0.838271  0.795257
6    Gradient Boosting  0.756101         0.726579      0.843366  0.780629
3        Random Forest  0.751307         0.718552      0.841892  0.775348
0  Logistic Regression  0.742245         0.724412      0.822832  0.770492
2        Decision Tree  0.697751         0.686281      0.781087  0.730621
8          Extra Trees  0.692813         0.656900      0.793234  0.718658
5          Naive Bayes  0.570408         0.832143      0.601451  0.698235
4                  SVM  0.670662         0.628321      0.777568  0.695023
1                  KNN  0.590257         0.538252      0.705864  0.610767

In [94]:
import pickle

pipeline=Pipeline([
    ('1',trf),
    ('2',GradientBoostingClassifier())
])
pipeline.fit(X_train,y_train)
y_pred = pipeline.predict(X_test)

print(y_pred[:10])

[0 1 1 0 1 0 0 0 1 1]

In [95]:
print(pipeline.predict_proba(X_test[:5]))

[[0.5876429  0.4123571 ]
 [0.11264031 0.88735969]
 [0.15430799 0.84569201]
 [0.51741043 0.48258957]
 [0.12447439 0.87552561]]

In [96]:
with open('pipe.pkl', 'wb') as f:
    pickle.dump(pipeline, f)